### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by twoATOMS** [davidbrochart/jpterm#28]
Hello, for some reasons jpterm does not work after I installed it.

After I open a notebook with it, it does not allow me to edit the cells or run them in any way.

Am I doing something wrong?

**Comment by davidbrochart** [comment]
Hi, it's not implemented yet :smile: 
#27 will allow to execute cells, but I think that for editing notebooks I will wait for Texual to implement `TextArea`.

**Comment by twoATOMS** [comment]
My mistake. Looking forward to it!

**Comment by julian-goldsmith** [comment]
General comment: I found it unclear from the documentation that jpterm isn't fully-featured yet.  The note in nbterm's README made me think jpterm was ready for daily use.

**Comment by davidbrochart** [comment]
Yes, I should mention in the README that jpterm is a work in progress.
