### ISSUE TITLE
commands  jpterm --server  not working

### ISSUE THREAD

**Issue by echidne** [davidbrochart/jpterm#54]
Os: Windows 10
Python: Python 3.11
Terminal: Powershell (Windows terminal)
to reproduce the error:
pip install "jupyterlab>=4"
pip install jupyter-collaboration
jupyter lab --port=8000 --no-browser
then in another terminal:
jpterm --server http://127.0.0.1:8000/?token=972cbd440db4b35581b25f90c0a88e3a1095534e18251ca8
or
jpterm --server http://127.0.0.1:8000

display  : 
![image](https://github.com/davidbrochart/jpterm/assets/65033881/b7619720-63bc-480a-9cc0-1f159b079332)

**Comment by davidbrochart** [comment]
> then in another terminal:
> jpterm --server http://127.0.0.1:8000/?token=972cbd440db4b35581b25f90c0a88e3a1095534e18251ca8

I see that this is the same token as on the README, but you need to replace it with whatever JupyterLab gave you. The command:
```bash
jupyter lab --port=8000 --no-browser
```
should print something like this in your terminal:
```
    To access the server, open this file in a browser:
        file:///home/david/.local/share/jupyter/runtime/jpserver-631663-open.html
    Or copy and paste one of these URLs:
        http://localhost:8000/lab?token=dec1420d65fc7a82f9dbdaa175be430eda5602083c82390a
        http://127.0.0.1:8000/lab?token=dec1420d65fc7a82f9dbdaa175be430eda5602083c82390a
````
Now you need to launch jpterm with:
```bash
jpterm --server http://127.0.0.1:8000/?token=dec1420d65fc7a82f9dbdaa175be430eda5602083c82390a
```
Note that it's the same URL without the `lab`.

**Comment by echidne** [comment]
I confirm it was the problem. thanks.
