### ISSUE TITLE
running cells

### ISSUE THREAD

**Issue by YanivDorGalron** [davidbrochart/jpterm#61]
how can i run cells? ctrl+enter / shift+enter doesnt work

**Comment by davidbrochart** [comment]
It's crtl+e (run and stay on the cell) or ctrl+r (run and move to the next cell).

**Comment by ooloth** [comment]
Any kind of usage docs (for things like this) would be great! 

The docs site currently includes [no instructions](https://davidbrochart.github.io/jpterm/usage/key_bindings.md) after the CLI page. (The other usage and code reference pages all 404.)

**Comment by davidbrochart** [comment]
Yes, that's on my todo list :)

**Comment by ooloth** [comment]
Thanks!
