### ISSUE TITLE
Version 0.2.9 is no longer listed on pypy

### ISSUE THREAD

**Issue by rgant** [davidbrochart/jpterm#86]
Trying this package out, added it to our dependencies last week when the current version was 0.2.9.

Today my coworker tries to sync dependencies and gets errors:

```
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement jpterm==0.2.9 (from versions: 0.2.11)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for jpterm==0.2.9
```

I appears that the past versions are not maintained on [pypy](https://pypi.org/project/jpterm/#history)
So now they cannot update dependencies and I must remove this package so I don't make my team's life difficult. 

I don't think this is a great first time experience for my team.

**Comment by davidbrochart** [comment]
Sorry @rgant, I discovered sensitive information was somehow shipped with the package, and I decided to delete all releases where this could have happened. But you can update to v0.2.11.
