### ISSUE TITLE
Inserting cells above and below nonfunctional.

### ISSUE THREAD

**Issue by saarantras** [davidbrochart/jpterm#89]
A and B. I tried with and without shift, and I'm certain I'm in command mode, but no cells were added. Executing a cell or editing its contents worked fine. These hotkeys are in the docs, are they implemented yet..? Do you need debug information?

**Comment by davidbrochart** [comment]
Could you share your environment?
- `pip list`
- are you in local mode or with a server?
- your notebook?

**Comment by saarantras** [comment]
The bug was happening consistently, after multiple restarts, but as soon as I went to reproduce to try and make a minimal example, it started working properly! If it stops working again I'll try and make a reproducible example.

**Comment by davidbrochart** [comment]
I'll close this issue then, feel free to re-open.
