### ISSUE TITLE
Running remote jupyter lab notebook and gathering stdout/stderr

### ISSUE THREAD

**Issue by jogomu** [davidbrochart/jpterm#9]
`jpterm --use-server http://127.0.0.1:8888 --run Untitled.ipynb`

I need to hit https://mynotebook (note: TLS) which requires a password to log in (the normal jupyter lab password feature) then run a notebook and collect the stdout/stderr from all the cells that were run.  I need the notebook to run either using the kernel spec associated with the notebook or ideally even specifying the kernel.  Don't need any charting or anything fancy.

Is this project close to providing this?  Anything I can do to help or background information I can read to take a shot at creating this functionality myself?  Is there another similar project somewhere that does this?

Thanks!

**Comment by davidbrochart** [comment]
This project has not really started yet. I'm waiting for the [css](https://github.com/Textualize/textual/tree/css) branch of Textual to be merged in main.

**Comment by davidbrochart** [comment]
@jogomu I added initial support for kernels in #27, but jpterm is still very early stage.
I'm closing this issue for now, feel free to re-open in the future!
